spring.application.name=gateway
server.port=8081

# Route config
services.backend.url=http://backend:8082
services.template.url=http://template:8083

# Private keys
spring.jwt.key=096c0a72c31f9a2d65126d8e8a401a2ab2f2e21d0a282a6ffe6642bbef65ffd9
spring.hmac.key=6a627a7fb025e2c5db643267523a1c801c1178bed30331a2606fe93f4dd9aa7b

# Spring settings
spring.jwt.expiration=12

# PostgreSQL connection (Supabase)
spring.datasource.url=jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.qzgrljhbhamarnqobeut
spring.datasource.password=j8Z98RKF91gQX0VW
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Hikari settings
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.keepalive-time=30000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.maximum-pool-size=3